// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebuldpfcckbbsdqnjstf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVidWxkcGZjY2tiYnNkcW5qc3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTUyMTUsImV4cCI6MjA2MjEzMTIxNX0.RcnLyRMkzCb1qngsu6UQGlXnI2HhPd9LxYygU_QL2Bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);